### ISSUE TITLE
Discord cashing when using the plugin

### ISSUE THREAD

**Issue by InternetNutzer** [thiaguinho4/MessageLoggerV2-Fixed-2023#1]
I have tried your fix, but still expierenced crashes, which is why i am writing this Issue.
-> I have deleted the config.json and Data.config.json in an attempt to fix the problem already

I have been able to narrow down the problem, to the fact, that discord crashes when someone edits a message and you try to open the chat in which this message is contrained.

I hope this information helps you and makes it possible for you to resolve it.
Good luck and keep up the work, we need people like you working on these projects :D

**Comment by thiaguinho4** [comment]
Thank you for the comment! It does not fix edits yet so you need to disable Display edited messages in chat if you don't want your BD crashing on message edit.

![image](https://user-images.githubusercontent.com/101910294/224198785-6ee869cc-e289-425e-9222-3a2ca8bb96cb.png)
