### ISSUE TITLE
Messagelogger doesnt run

### ISSUE THREAD

**Issue by Jeez1221** [thiaguinho4/MessageLoggerV2-Fixed-2023#2]
messagelogger fails to start and gives this message, i reinstalled betterdiscord and reloaded discord

**Comment by Jeez1221** [comment]
reinstalled and the xeno lib works but the messagelogger doesnt run

**Comment by Jeez1221** [comment]
![image](https://user-images.githubusercontent.com/91221944/224250778-6b347cfd-e117-43fd-9468-b4817ab65087.png)

**Comment by thiaguinho4** [comment]
I'm going to leave this issue open for now because i've noticed this for a while and I'm looking into it.

**Comment by thiaguinho4** [comment]
**[Download](https://github.com/thiaguinho4/MessageLoggerV2-Fixed-2023/releases)** the new version with this error fixed!
